version: '3.7'

volumes:
  logs:
    driver: local
  db_data:
    driver: local
services:
    slim:
        build: 
           context: .
           dockerfile: ./build/Dockerfile
        working_dir: /var/www
        environment:
            docker: "true"
        ports:
            - "8080:8080"
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: toubilib_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: toubilib
            MYSQL_USER: toubilibprojet
            MYSQL_PASSWORD: toubi
        ports:
            - "3306:3306"
        volumes:
            - ./sql:/docker-entrypoint-initdb.d
            - db_data:/var/lib/mysql

    adminer:
        image: adminer
        container_name: toubilib_adminer
        ports:
            - "8081:8080"
        depends_on:
            - db
